wordpress:
     build: .
     container_name: wordpress-ssl
     ports:
       - "8090:80"
       - "8443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 192.168.64.2:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: Wrpvs655321or
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - {caminho/servidor/certs}:/etc/ssl/certs/
       - {caminho/servidor/privates/}:/etc/ssl/private/ 
