wordpress:
     build: .
     container_name: wordpress-ssl
     ports:
       - "8090:80"
       - "8443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: IP_DO_BANCO:PORTA
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: suasenhafoda
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - /etc/letsencrypt/archive/{APLICATION_NAME}/:/etc/letsencrypt/archive/{APLICATION_NAME}/
       - /etc/letsencrypt/live/{APLICATION_NAME}/:/etc/letsencrypt/live/{APLICATION_NAME}/
